export const redirects = JSON.parse("{}")

export const routes = Object.fromEntries([
  ["/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/index.html.js"), meta: {"title":"Home"} }],
  ["/posts/202404131457.html", { loader: () => import(/* webpackChunkName: "202404131457.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/posts/202404131457.html.js"), meta: {"_blog":{"title":"記事ファイル作成スクリプトを作った","author":"","date":"2024-04-13T00:00:00.000Z","category":["misc"],"tag":["Node.js","ts-node"],"excerpt":"\n<ul>\n<li>Node.js v20.10.0</li>\n</ul>\n<p>VuePress で記事を書くときにファイル名を考えること、作成することが面倒だったためスクリプトを実行して半自動的にファイルを作成することにした。</p>\n<p>スクリプトは TypeScript で書きたいので ts-node をインストールしてスクリプトを実行したところ下記のエラーが発生した。</p>\n<div class=\"language-text\" data-ext=\"text\" data-title=\"text\"><pre class=\"language-text\"><code>TypeError: Unknown file extension \".ts\"\n</code></pre></div>"},"title":"記事ファイル作成スクリプトを作った"} }],
  ["/posts/202404141109.html", { loader: () => import(/* webpackChunkName: "202404141109.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/posts/202404141109.html.js"), meta: {"_blog":{"title":"VuePress で作ったサイトを公開","author":"","date":"2024-04-14T00:00:00.000Z","category":["misc"],"tag":["GitHub Pages"],"excerpt":"\n<p>GitHub Pages を使うのは初めてだったが簡単に公開まで出来た。\nGitHub ワークフローの設定を <code>.github/workflows/deploy-docs.yml</code> に書いているので、main ブランチにプッシュすることでワークフローが開始、gh-pages ブランチにビルドされたコードがデプロイされる。GitHub のリポジトリ設定で利用するブランチを gh-pages に指定すれば公開された URL を確認できる。</p>\n"},"title":"VuePress で作ったサイトを公開"} }],
  ["/posts/202404240024.html", { loader: () => import(/* webpackChunkName: "202404240024.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/posts/202404240024.html.js"), meta: {"_blog":{"title":"同名省略記法","author":"","date":"2024-04-24T00:00:00.000Z","category":["Front-End"],"tag":["Vue.js"],"excerpt":"\n<p>バインドする値と属性が同じ名前を持っている場合、下記のように省略した記法ができる。\nVue3.4以上から使用できる。</p>\n<p>小さいコンポーネントであれば使う機会がありそう。</p>\n<div class=\"language-vue\" data-ext=\"vue\" data-title=\"vue\"><pre class=\"language-vue\"><code><span class=\"token tag\"><span class=\"token tag\"><span class=\"token punctuation\">&lt;</span>script</span> <span class=\"token attr-name\">setup</span> <span class=\"token attr-name\">lang</span><span class=\"token attr-value\"><span class=\"token punctuation attr-equals\">=</span><span class=\"token punctuation\">\"</span>ts<span class=\"token punctuation\">\"</span></span><span class=\"token punctuation\">&gt;</span></span><span class=\"token script\"><span class=\"token language-javascript\">\n<span class=\"token keyword\">const</span> id <span class=\"token operator\">=</span> <span class=\"token string\">'hoge'</span>\n</span></span><span class=\"token tag\"><span class=\"token tag\"><span class=\"token punctuation\">&lt;/</span>script</span><span class=\"token punctuation\">&gt;</span></span>\n<span class=\"token tag\"><span class=\"token tag\"><span class=\"token punctuation\">&lt;</span>template</span><span class=\"token punctuation\">&gt;</span></span>\n  <span class=\"token tag\"><span class=\"token tag\"><span class=\"token punctuation\">&lt;</span>div</span> <span class=\"token attr-name\">:id</span><span class=\"token punctuation\">&gt;</span></span>hoge<span class=\"token tag\"><span class=\"token tag\"><span class=\"token punctuation\">&lt;/</span>div</span><span class=\"token punctuation\">&gt;</span></span>\n<span class=\"token tag\"><span class=\"token tag\"><span class=\"token punctuation\">&lt;/</span>template</span><span class=\"token punctuation\">&gt;</span></span>\n</code></pre></div>"},"title":"同名省略記法"} }],
  ["/posts/202404251328.html", { loader: () => import(/* webpackChunkName: "202404251328.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/posts/202404251328.html.js"), meta: {"_blog":{"title":"disabled 属性は空でも truthy になる","author":"","date":"2024-04-25T00:00:00.000Z","category":["Front-End"],"tag":["Vue.js"],"excerpt":"\n<p>disabled 属性は空の場合も truthy になるので注意。\n基本的には boolean によって disabled 属性の付け外しを行うのが紛らわしくなくて良い。</p>\n<div class=\"language-vue\" data-ext=\"vue\" data-title=\"vue\"><pre class=\"language-vue\"><code><span class=\"token tag\"><span class=\"token tag\"><span class=\"token punctuation\">&lt;</span>input</span> <span class=\"token attr-name\">type</span><span class=\"token attr-value\"><span class=\"token punctuation attr-equals\">=</span><span class=\"token punctuation\">\"</span>text<span class=\"token punctuation\">\"</span></span> <span class=\"token attr-name\">disabled</span><span class=\"token attr-value\"><span class=\"token punctuation attr-equals\">=</span><span class=\"token punctuation\">\"</span><span class=\"token punctuation\">\"</span></span><span class=\"token punctuation\">&gt;</span></span>\n</code></pre></div>"},"title":"disabled 属性は空でも truthy になる"} }],
  ["/posts/202405150029.html", { loader: () => import(/* webpackChunkName: "202405150029.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/posts/202405150029.html.js"), meta: {"_blog":{"title":"リアクティブは ref が推奨される","author":"","date":"2024-05-15T00:00:00.000Z","category":["Front-End"],"tag":["Vue.js"],"excerpt":"\n<p>以下の理由によりリアクティブな状態の宣言は ref が推奨されるとのこと。\n分割代入はうっかりやりそうだなと思った。</p>\n<ul>\n<li>オブジェクト型に対してのみ機能する</li>\n<li>オブジェクト全体を置換できない</li>\n<li>分割代入できない</li>\n</ul>\n<p><a href=\"https://ja.vuejs.org/guide/essentials/reactivity-fundamentals.html#limitations-of-reactive\" target=\"_blank\" rel=\"noopener noreferrer\">reactive()の制限</a></p>"},"title":"リアクティブは ref が推奨される"} }],
  ["/posts/202405181111.html", { loader: () => import(/* webpackChunkName: "202405181111.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/posts/202405181111.html.js"), meta: {"_blog":{"title":"QCD とは","author":"","date":"2024-05-18T00:00:00.000Z","category":["misc"],"tag":["quality","QCD"],"excerpt":"\n<blockquote>\n<p>QCDFとは、品質(Quality)、価格(Cost)、納期や入手性(Delivery)、柔軟性(Flexibility)の頭文字をとったもので、製造業における開発生産業務の評価における指標のひとつである。</p>\n</blockquote>\n<blockquote>\n<p>よりよいものを生産するための資料とする。</p>\n</blockquote>\n<p><a href=\"https://ja.wikipedia.org/wiki/QCDF\" target=\"_blank\" rel=\"noopener noreferrer\">引用元</a></p>\n<p>「よりよいものを生産するため」という言葉はシステム開発の品質管理においても共感できる。</p>"},"title":"QCD とは"} }],
  ["/posts/202407090910.html", { loader: () => import(/* webpackChunkName: "202407090910.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/posts/202407090910.html.js"), meta: {"_blog":{"title":"Slack通知を試してみた","author":"","date":"2024-07-09T00:00:00.000Z","category":["misc"],"tag":["Slack"],"excerpt":"\n<p>GitHub のリポジトリに push したら Slack に通知する仕組みを作ってみた。</p>\n<h2>方法</h2>\n<ul>\n<li>Slack で Incoming Webhooks の設定をする</li>\n<li>Webhook URL を GitHub の対象リポジトリの Settings にて Secrets に設定する</li>\n<li>Secrets に設定した定数を用いて .github/workflows/slack-notify.yml を作成する</li>\n</ul>\n"},"title":"Slack通知を試してみた"} }],
  ["/posts/202407131543.html", { loader: () => import(/* webpackChunkName: "202407131543.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/posts/202407131543.html.js"), meta: {"_blog":{"title":"トリプルスラッシュ・ディレクティブ","author":"","date":"2024-07-13T00:00:00.000Z","category":["Front-End"],"tag":["TypeScript"],"excerpt":"\n<p><a href=\"https://histoire.dev/guide/vue3/getting-started.html#typescript\" target=\"_blank\" rel=\"noopener noreferrer\">Histoire</a> を使う際の型定義で初めて目にした。</p>\n<div class=\"language-typescript\" data-ext=\"ts\" data-title=\"ts\"><pre class=\"language-typescript\"><code><span class=\"token comment\">/// &lt;reference types=\"@histoire/plugin-vue/components\" /&gt;</span>\n</code></pre></div>"},"title":"トリプルスラッシュ・ディレクティブ"} }],
  ["/posts/202408101325.html", { loader: () => import(/* webpackChunkName: "202408101325.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/posts/202408101325.html.js"), meta: {"_blog":{"title":"Biome は一旦お預け","author":"","date":"2024-08-10T00:00:00.000Z","category":["Front-End"],"tag":["formatter"],"excerpt":"\n<p>コードフォーマットの機能がある Biome は .vue ファイルは <code>&lt;script&gt;</code> タグ部分のみが現在サポートされている。</p>\n<p><a href=\"https://biomejs.dev/ja/internals/language-support/#:~:text=.vue%20%E3%81%8A%E3%82%88%E3%81%B3%20.svelte%20%E3%83%95%E3%82%A1%E3%82%A4%E3%83%AB%E3%81%A7%E3%81%AF%E3%80%81%3Cscript%3E%E3%82%BF%E3%82%B0%E9%83%A8%E5%88%86%E3%81%AE%E3%81%BF%E3%81%8C%E3%82%B5%E3%83%9D%E3%83%BC%E3%83%88%E3%81%95%E3%82%8C%E3%81%A6%E3%81%84%E3%81%BE%E3%81%99%E3%80%82\" target=\"_blank\" rel=\"noopener noreferrer\">参照</a></p>"},"title":"Biome は一旦お預け"} }],
  ["/posts/202408112150.html", { loader: () => import(/* webpackChunkName: "202408112150.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/posts/202408112150.html.js"), meta: {"_blog":{"title":"import のファイルパス補完には tsconfig の設定が必要","author":"","date":"2024-08-11T00:00:00.000Z","category":["Front-End"],"tag":["Vite"],"excerpt":"\n<p>Vite 環境、VSCode でコーディングするときに、パスの補完がされないと自力で相対パスを書かないといけないので面倒すぎる。</p>\n<p>必要な設定は2つ。</p>\n<p>vite 設定 の resolve.alias に解決したいパスを指定。</p>\n<div class=\"language-vite.config.mjs\" data-ext=\"vite.config.mjs\" data-title=\"vite.config.mjs\"><pre class=\"language-vite.config.mjs\"><code>export default defineConfig({\n  plugins: [vue()],\n  resolve: {\n    alias: {\n      '@': fileURLToPath(new URL('./src', import.meta.url))\n    }\n  }\n})\n</code></pre></div>"},"title":"import のファイルパス補完には tsconfig の設定が必要"} }],
  ["/posts/202408171014.html", { loader: () => import(/* webpackChunkName: "202408171014.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/posts/202408171014.html.js"), meta: {"_blog":{"title":"CSS の clamp 関数を使ってみた","author":"","date":"2024-08-17T00:00:00.000Z","category":["Front-End"],"tag":["CSS","clamp"],"excerpt":"\n<p>clamp とは CSS の数学関数の1つ。\n使い方はこう。</p>\n<div class=\"language-css\" data-ext=\"css\" data-title=\"css\"><pre class=\"language-css\"><code><span class=\"token property\">width</span><span class=\"token punctuation\">:</span> <span class=\"token function\">clamp</span><span class=\"token punctuation\">(</span>最小値<span class=\"token punctuation\">,</span>推奨値<span class=\"token punctuation\">,</span>最大値<span class=\"token punctuation\">)</span><span class=\"token punctuation\">;</span>\n</code></pre></div>"},"title":"CSS の clamp 関数を使ってみた"} }],
  ["/posts/202410121204.html", { loader: () => import(/* webpackChunkName: "202410121204.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/posts/202410121204.html.js"), meta: {"_blog":{"title":"ソフトスキルの重要性に気づく","author":"","date":"2024-10-12T00:00:00.000Z","category":["misc"],"tag":["ソフトスキル","ハードスキル"],"excerpt":"\n<p>自身の振り返り・自己分析をしていたら「ソフトスキル」という言葉にぶつかった。\nどこかでうっすら聞いた覚えはあるが何なのかは知らないので調べてみる。</p>\n<h2>ソフトスキル</h2>\n<p>コミュニケーション力、リーダーシップ、問題解決力、柔軟性、協調性などがそれにあたるらしい。\nある記事でシステム開発に求められるスキルということで以下が紹介されていたが、ソフトスキルの説明と共通している部分がある。</p>\n<ul>\n<li>プログラミングスキル</li>\n<li>コミュニケーション能力</li>\n<li>論理的思考力</li>\n<li>提案力</li>\n<li>傾聴力</li>\n<li>タスクマネジメント力</li>\n</ul>"},"title":"ソフトスキルの重要性に気づく"} }],
  ["/posts/202410121237.html", { loader: () => import(/* webpackChunkName: "202410121237.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/posts/202410121237.html.js"), meta: {"_blog":{"title":"VitePress について調べてみる","author":"","date":"2024-10-12T00:00:00.000Z","category":["Front-End"],"tag":["VitePress"],"excerpt":"\n<p>本ブログを VuePress から VitePress に移行しようと思っているので VitePress について調べることにする。</p>\n<h2>VitePress とは</h2>\n<p>高速でコンテンツ中心のウェブサイトを構築するよう設計された静的サイトジェネレータ。\nコンテンツは Markdown で書かれる。</p>\n<p>Vue.js の公式ドキュメントも VitePress で作られているらしい。</p>\n<p>Vite + Vue で作られているからカスタマイズもしやすいと。</p>\n<h2>VuePress と VitePress の違い</h2>\n<p>VuePress は Vue + webpack。\nVitePress は Vue + vite。</p>"},"title":"VitePress について調べてみる"} }],
  ["/404.html", { loader: () => import(/* webpackChunkName: "404.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/404.html.js"), meta: {"title":""} }],
  ["/category/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/category/index.html.js"), meta: {"title":"Categories"} }],
  ["/category/misc/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/category/misc/index.html.js"), meta: {"title":"Category misc"} }],
  ["/category/front-end/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/category/front-end/index.html.js"), meta: {"title":"Category Front-End"} }],
  ["/tag/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/tag/index.html.js"), meta: {"title":"Tags"} }],
  ["/tag/node.js/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/tag/node.js/index.html.js"), meta: {"title":"Tag Node.js"} }],
  ["/tag/ts-node/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/tag/ts-node/index.html.js"), meta: {"title":"Tag ts-node"} }],
  ["/tag/github-pages/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/tag/github-pages/index.html.js"), meta: {"title":"Tag GitHub Pages"} }],
  ["/tag/vue.js/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/tag/vue.js/index.html.js"), meta: {"title":"Tag Vue.js"} }],
  ["/tag/quality/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/tag/quality/index.html.js"), meta: {"title":"Tag quality"} }],
  ["/tag/qcd/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/tag/qcd/index.html.js"), meta: {"title":"Tag QCD"} }],
  ["/tag/slack/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/tag/slack/index.html.js"), meta: {"title":"Tag Slack"} }],
  ["/tag/typescript/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/tag/typescript/index.html.js"), meta: {"title":"Tag TypeScript"} }],
  ["/tag/formatter/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/tag/formatter/index.html.js"), meta: {"title":"Tag formatter"} }],
  ["/tag/vite/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/tag/vite/index.html.js"), meta: {"title":"Tag Vite"} }],
  ["/tag/css/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/tag/css/index.html.js"), meta: {"title":"Tag CSS"} }],
  ["/tag/clamp/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/tag/clamp/index.html.js"), meta: {"title":"Tag clamp"} }],
  ["/tag/%E3%82%BD%E3%83%95%E3%83%88%E3%82%B9%E3%82%AD%E3%83%AB/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/tag/ソフトスキル/index.html.js"), meta: {"title":"Tag ソフトスキル"} }],
  ["/tag/%E3%83%8F%E3%83%BC%E3%83%89%E3%82%B9%E3%82%AD%E3%83%AB/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/tag/ハードスキル/index.html.js"), meta: {"title":"Tag ハードスキル"} }],
  ["/tag/vitepress/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/tag/vitepress/index.html.js"), meta: {"title":"Tag VitePress"} }],
  ["/article/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/article/index.html.js"), meta: {"title":"Articles"} }],
  ["/timeline/", { loader: () => import(/* webpackChunkName: "index.html" */"/Users/okazawashinya/Documents/vuepress-blog/docs/.vuepress/.temp/pages/timeline/index.html.js"), meta: {"title":"Timeline"} }],
]);

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updateRoutes) {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
  }
  if (__VUE_HMR_RUNTIME__.updateRedirects) {
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ routes, redirects }) => {
    __VUE_HMR_RUNTIME__.updateRoutes(routes)
    __VUE_HMR_RUNTIME__.updateRedirects(redirects)
  })
}
